root: true

extends:
  - airbnb
  - plugin:promise/recommended
  - plugin:prettier/recommended
  - prettier/react
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: false

settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .tsx
        - .js
        - .jsx

rules:
  # consoleは限定
  no-console:
    - error
    - allow: [debug, warn, error]

  # case の break 省略はエラー / fall through コメントで抑制
  no-fallthrough:
    - error

  # default export は使わない
  import/prefer-default-export:
    - off
  import/no-default-export:
    - error

  # importの順
  import/order:
    - error
    - newlines-between: always

  # importで拡張子は不要
  import/extensions:
    - error
    - never

  # 適当に空行が入るようにする
  padding-line-between-statements:
    - error
    - { blankLine: always, prev: '*', next: return }
    - { blankLine: any, prev: export, next: export }
    - { blankLine: always, prev: '*', next: if }
    - { blankLine: always, prev: '*', next: const }
    - { blankLine: always, prev: const, next: '*' }
    - { blankLine: any, prev: const, next: const }
    - { blankLine: always, prev: case, next: '*' }

  # 適当に空行が入るようにする
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true

  # 関数はconstで定義する
  func-style:
    - error
    - expression

  # 引数のプロパティ操作禁止
  no-param-reassign:
    - error
    - props: true
      # コンテキスト的なものは許可
      ignorePropertyModificationsFor:
        - ctx
        - context

  ### for React

  # tsx を許容
  react/jsx-filename-extension:
    - error
    - extensions: ['.jsx', '.tsx']

  ### for TypeScript

  # 戻り値の型は常に必要
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true # 引数のコールバックなどは省略可

  # 先頭が_の変数は使ってなくても良い
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
